[versions]
agp = "9.4.0"
android-compile-sdk = "34" # 编译版本
android-min-sdk = "21" # 最小版本
android-target-sdk = "30"# 目标版本
appcompat = "1.7.1"
asm-util = "9.9.1"
auto-service = "1.1.1"
commons-codec = "1.20.0"
commons-collections4 = "4.5.0"
commons-io = "2.16.1"
commons-lang3 = "3.20.0"
constraintlayout = "2.2.1"
coreKtx = "1.13.1"
espresso-core = "3.7.0"
fastjson = "1.2.83"
gson = "2.13.2"
hilt = "2.57.2" #注入依赖 https://dagger.dev/hilt/
javapoet = "1.13.0"
junit = "4.13.2"
junitVersion = "1.3.0"
kotlin = "2.3.0"
kotlinpoet = "2.2.0"
ksp = "2.3.3" # https://github.com/google/ksp/releases
link-builder = "2.0.5" #超链接处理 https://github.com/klinker24/Android-TextView-LinkBuilder
material = "1.13.0"
router = "2.0.8" #https://github.com/lany192/app-router
toaster = "12.6" #Toast工具 https://github.com/getActivity/Toaster

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-test-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
androidx-test-ext-junit2 = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
asm-util = { module = "org.ow2.asm:asm-util", version.ref = "asm-util" }
auto-service-annotations = { module = "com.google.auto.service:auto-service-annotations", version.ref = "auto-service" }
auto-service-compiler = { module = "com.google.auto.service:auto-service", version.ref = "auto-service" }
commons-codec = { module = "commons-codec:commons-codec", version.ref = "commons-codec" }
commons-collections4 = { module = "org.apache.commons:commons-collections4", version.ref = "commons-collections4" }
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang3" }
fastjson = { module = "com.alibaba:fastjson", version.ref = "fastjson" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
javapoet = { module = "com.squareup:javapoet", version.ref = "javapoet" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinpoet" }
kotlinpoet-metadata = { module = "com.squareup:kotlinpoet-metadata", version.ref = "kotlinpoet" }
ksp-symbol-processing-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
lany-router = { module = "com.github.lany192.app-router:arouter", version.ref = "router" }
lany-router-compiler = { module = "com.github.lany192.app-router:arouter-compiler", version.ref = "router" }
lany-router-register = { module = "com.github.lany192.app-router:arouter-register", version.ref = "router" }
link-builder = { module = "com.klinkerapps:link_builder", version.ref = "link-builder" }
toaster = { module = "com.github.getActivity:Toaster", version.ref = "toaster" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
android-legacy-kapt = { id = "com.android.legacy-kapt", version.ref = "agp" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

